CREATE DATABASE uc11;
USE uc11;

CREATE TABLE produtos (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome TEXT DEFAULT NULL,
  valor INT(11) DEFAULT NULL,
  status TEXT DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE USER 'leiloes'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON uc11.* TO 'leiloes'@'localhost';